id: P000336
initial_creation_type: ocr
created_at: 13/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG22189
  title: བདེ་གཤེགས་འདུས་པ་སྒྲུབ་པ་བཀའ་བརྒྱད་སྐོར།
  author: ''
  volumes:
    66e1897f6fc24f6981ad279fda95ecc3:
      image_group_id: I1KG22343
      title: Volume 1 of bde gshegs 'dus pa sgrub pa bka' brgyad skor/
      volume_number: 1
      total_pages: 506
      base_file: v001.txt
