id: opecha:P000336
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22189
  title: བདེ་གཤེགས་འདུས་པ་སྒྲུབ་པ་བཀའ་བརྒྱད་སྐོར།
  volume:
    66e1897f6fc24f6981ad279fda95ecc3:
      image_group_id: I1KG22343
      title: Volume 1 of bde gshegs 'dus pa sgrub pa bka' brgyad skor/
      volume_number: 1
      total_pages: 506
  author: ''
ebook_metadata:
  title: བདེ་གཤེགས་འདུས་པ་སྒྲུབ་པ་བཀའ་བརྒྱད་སྐོར།
  author: ''
  sku: P000336
  cover: cover.jpg
  layers:
  - pagination
