id: I47E5E8A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T12:12:26+00:00'
last_modified: '2022-06-10T04:38:11.929869+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22189
  title: བདེ་གཤེགས་འདུས་པ་སྒྲུབ་པ་བཀའ་བརྒྱད་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    939A:
      image_group_id: I1KG22343
      title: Volume 1 of bde gshegs 'dus pa sgrub pa bka' brgyad skor/
      total_pages: 506
      order: 1
      base_file: 939A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
